### PR TITLE
Fixed uv_run_once + added a return value

### PR DESCRIPTION
**Pull request by csaoh**
I noticed libuv doesn't use uv_run_once but uv_run(loop, UV_RUN_ONCE) instead, so I couldn't make php-uv to work anymore.

### CODE REVIEW

**Comment by csaoh** [comment]
@chobie I also took the liberty to add a return value to uv_run_once. Theoretically it should return 0 if there are no more events in the queue. This should allow replacing uv_run by a loop of uv_run_once, and with this I was able to implement stop and resume methods within react-php.

Hope it's ok for you.

**Comment by csaoh** [comment]
Fixed. I got kind of messed up in commits though...

**Comment by csaoh** [comment]
Do you want me to close all of this, make sure i'm up-to-date and reopen another PR ? Or you will simply drop the uv_run_once ?

**Comment by chobie** [comment]
for now, i'll merge your PR :smile:

**Pull request closed without merging**
